language: node_js
node_js:
  - node
services: mongodb
install:
  - npm install -g mocha
  - npm install chai
  - npm install chai-http
  - npm install express
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: y8fCED8JJm0PHeCDtFJjYXCZRlANADMf1dIHUWqk4IiGSekoY4MJ59FA7cghUPcObdRl/gPSluSz/AxBFyJZ+2hSQLP5OlpS8iMTORhRxP/jFXDQtJ1miyLNAftFWwXBi8GIo0wUifdb+OqXE1XcvNU/M0217OqiuXLbHMkcIcBCXg6vRSrlWelcJsU1SqWqdS4lvtGFvfOZsXA3+v3fr/C2Du8Mw7kqPK41I8CQHI9SWCr2BdVye3spJnncmxuEGZ0cxTa8/vjesQl05JT0Sw4dUmvDQ961TDnbJU3cTVtt6kt1fFLpM1VLxYNDF/2ZHcAlFCFuu+RrceGfx7tKwM5OUTX3WwFUDJS+CY7e/qYXpa36zDFSqpQ8/471X5BnJ6mAtymrP/GUQn8zPoSWw+pdml700fGtivG6ODymHKwl/adw3fUdGtDQfbYuendXJQmzFOPDm0qvMa3brfUts51rR2XwoMQgl0wHylkq4WBb3b/0er5AeJFIc2biVZH0BaSOjS6y4XP8ZaDcXaGvbiuzkqluUla5alxkCt0f68wPBsveuwmksiXRSLPj6IjJZPETwHJ4p0+S3tnD0aUDpUGMCctFhMsMdvPb9N0DXX+59mQKFp67zwICLlHufresCMckZU9HKPhbdER2gV47Jt99n27IBL1g8KVQpBdvxt8=
  app: comp3006-connect-four
  on:
    repo: GoelBiju/COMP3006-Full-Stack-Project
    branch: main
  cleanup: "true"
