language: node_js
node_js:
- node
install:
- npm install -g mocha
- npm install chai
- npm install chai-http
- npm install express
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: cj3mJ4VvVQO5LSnDND9yZFbkLrPy8FoD25OEzXQx4eWv3kS1LNCfyfdgDJxWG9uxx9w1ojviAOI52DhBAyRzHSc6H0bB952CK+4boHfUeCGcBzt8+s4w8CxSXbJhSPUqCdOQCGPcTa8jQ4iClYBjcjQaRGz2r0+PE2TK9+eL4qMpHGnYWW1xtaUG6wr3EPDCzakYapgJ+nKiQ2Sy2p92pEEHMN46XYP0mBPW4dCP7K1mBXlD2+8Jwl/QgRk/c7X4Y1DZeQCfxBvy+l0DgZb818mQZaf936H8NuiFWsClaUFrDxa/sIgdy33Ee1U0XYK4jwrQ4DoqvZudKd6m2lhwjDUI84sKeZP2nUMLva5aYCKpUzPoHWXjww7fE1LyNBmbQyVVfiZmZhf+E8HlqH1kbbUGu9LXNK2UD/MseObp81XOcD8fz10Nw334OVLuqXMApXYelT91P2mc77ovNabnZOx9bAmnWizbstGQAKh3zrJs/xxw6h8Weffs3UtunVXSLL3qT4C2OCZu4/cLJ0H0uBNDsHFNx9uSSpeRpzVdzwzjYDVKwG8YF0ZFZtLIX2YNXvHQOGm6Yx3xxFWKCjnQ71G6vc6RMkwAOK1PpuECP+Hb6edl9b1m/E45lI0SkF7nI4h3kg3zvKIl4oDLd1ERbJ2jfTLvr/ioSwUuRef1EZE=
  app: COMP3006-Full-Stack-Project
  on:
    repo: GoelBiju/COMP3006-Full-Stack-Project
    branch: bugfix/heroku-key
  skip_cleanup: 'true'
